### ISSUE TITLE
decode() from stdout

### ISSUE THREAD

**Issue by cnascim1** [eastgenomics/eggd_optimised_filtering#15] opened 2024-02-15 14:33 UTC
https://github.com/eastgenomics/eggd_optimised_filtering/blob/35bf17da8ad60884e7619d8ba200978198012164/resources/utils/vcf.py#L114

decode() from stdout will originate strings and this will impact 
assert post_split >= pre_split 

ex:
>>> assert "1251" > "111"
>>> assert "1251" > "131"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError

**Comment by chrispyatt** [comment] 2024-02-26 14:44
Could you elaborate on what the problem is? I've never seen an assertion error occur at this point.

**Comment by rklocke** [comment] 2024-02-26 16:36
Fixed in PR #16

**Closed by rklocke** 2024-02-26 16:36 UTC
